// <auto-generated />
using System;
using ClinicaApi.Data;
using IBM.EntityFrameworkCore;
using IBM.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ClinicaApi.Migrations
{
    [DbContext(typeof(ClinicaDbContext))]
    [Migration("20261008192128_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseDb2IdentityColumns()
                .HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("ClinicaApi.Models.CentroCosto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseDb2IdentityColumn();

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(32672)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(32672)");

                    b.HasKey("Id");

                    b.ToTable("CentrosCosto");
                });

            modelBuilder.Entity("ClinicaApi.Models.InsumoMedico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseDb2IdentityColumn();

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(32672)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("StockGlobal")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.ToTable("Insumos");
                });

            modelBuilder.Entity("ClinicaApi.Models.TransaccionInventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseDb2IdentityColumn();

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("CentroCostoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaTransaccion")
                        .HasColumnType("timestamp(6)");

                    b.Property<int>("InsumoMedicoId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioResponsable")
                        .IsRequired()
                        .HasColumnType("varchar(32672)");

                    b.HasKey("Id");

                    b.HasIndex("CentroCostoId");

                    b.HasIndex("InsumoMedicoId");

                    b.ToTable("Transacciones");
                });

            modelBuilder.Entity("ClinicaApi.Models.TransaccionInventario", b =>
                {
                    b.HasOne("ClinicaApi.Models.CentroCosto", "CentroCosto")
                        .WithMany("Transacciones")
                        .HasForeignKey("CentroCostoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaApi.Models.InsumoMedico", "Insumo")
                        .WithMany("Transacciones")
                        .HasForeignKey("InsumoMedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CentroCosto");

                    b.Navigation("Insumo");
                });

            modelBuilder.Entity("ClinicaApi.Models.CentroCosto", b =>
                {
                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("ClinicaApi.Models.InsumoMedico", b =>
                {
                    b.Navigation("Transacciones");
                });
#pragma warning restore 612, 618
        }
    }
}
